<a href="https://colab.research.google.com/github/Saiful-2/telco-customer-churn/blob/main/notebooks/08_machine_learning_baseline_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Telecom Customer Churn - Baseline Models**

In [1]:
# =========================================
# 1. Import Required Libraries
# =========================================

import pandas as pd
import numpy as np

In [2]:
# =========================================
# 2. Import Machine Learning Libraries
# =========================================

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier

from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import GaussianNB

In [3]:
# =========================================
# 3. Import Evaluation Libraries
# =========================================

from sklearn.metrics import accuracy_score

from sklearn.metrics import precision_score

from sklearn.metrics import recall_score

from sklearn.metrics import f1_score

from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report

In [4]:
# =========================================
# 4. Load Training Dataset
# =========================================

X_train = pd.read_csv(
    "https://raw.githubusercontent.com/Saiful-2/datasets/main/X_train_scaled.csv"
)

y_train = pd.read_csv(
    "https://raw.githubusercontent.com/Saiful-2/datasets/main/y_train.csv"
)

In [5]:
# =========================================
# 5. Load Testing Dataset
# =========================================

X_test = pd.read_csv(
    "https://raw.githubusercontent.com/Saiful-2/datasets/main/X_test_scaled.csv"
)

y_test = pd.read_csv(
    "https://raw.githubusercontent.com/Saiful-2/datasets/main/y_test.csv"
)

In [6]:
# =========================================
# 6. Convert Target Variable into Series
# =========================================

y_train = y_train.squeeze()

y_test = y_test.squeeze()

In [7]:
# =========================================
# 7. Check Dataset Shapes
# =========================================

print(X_train.shape)

print(X_test.shape)

print(y_train.shape)

print(y_test.shape)

(5625, 29)
(1407, 29)
(5625,)
(1407,)

In [8]:
# =========================================
# 8. Logistic Regression Model
# =========================================

lr = LogisticRegression(
    random_state=42,
    max_iter=1000
)

lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [9]:
# =========================================
# 9. Logistic Regression Prediction
# =========================================

lr_pred = lr.predict(X_test)

In [10]:
# =========================================
# 10. Logistic Regression Evaluation
# =========================================

print("Accuracy:",
      accuracy_score(y_test, lr_pred))

print("Precision:",
      precision_score(y_test, lr_pred))

print("Recall:",
      recall_score(y_test, lr_pred))

print("F1 Score:",
      f1_score(y_test, lr_pred))

Accuracy: 0.7882018479033405
Precision: 0.6165644171779141
Recall: 0.5374331550802139
F1 Score: 0.5742857142857143

In [11]:
# =========================================
# 11. Decision Tree Model
# =========================================

dt = DecisionTreeClassifier(
    random_state=42
)

dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [12]:
# =========================================
# 12. Decision Tree Prediction
# =========================================

dt_pred = dt.predict(X_test)

In [13]:
# =========================================
# 13. Decision Tree Evaluation
# =========================================

print("Accuracy:",
      accuracy_score(y_test, dt_pred))

print("Precision:",
      precision_score(y_test, dt_pred))

print("Recall:",
      recall_score(y_test, dt_pred))

print("F1 Score:",
      f1_score(y_test, dt_pred))

Accuracy: 0.7313432835820896
Precision: 0.4949238578680203
Recall: 0.5213903743315508
F1 Score: 0.5078125

In [14]:
# =========================================
# 14. KNN Model
# =========================================

knn = KNeighborsClassifier(
    n_neighbors=5
)

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [15]:
# =========================================
# 15. KNN Prediction
# =========================================

knn_pred = knn.predict(X_test)

In [16]:
# =========================================
# 16. KNN Evaluation
# =========================================

print("Accuracy:",
      accuracy_score(y_test, knn_pred))

print("Precision:",
      precision_score(y_test, knn_pred))

print("Recall:",
      recall_score(y_test, knn_pred))

print("F1 Score:",
      f1_score(y_test, knn_pred))

Accuracy: 0.7697228144989339
Precision: 0.5683060109289617
Recall: 0.5561497326203209
F1 Score: 0.5621621621621622

In [17]:
# =========================================
# 17. Naive Bayes Model
# =========================================

nb = GaussianNB()

nb.fit(X_train, y_train)

GaussianNB()

In [18]:
# =========================================
# 18. Naive Bayes Prediction
# =========================================

nb_pred = nb.predict(X_test)

In [19]:
# =========================================
# 19. Naive Bayes Evaluation
# =========================================

print("Accuracy:",
      accuracy_score(y_test, nb_pred))

print("Precision:",
      precision_score(y_test, nb_pred))

print("Recall:",
      recall_score(y_test, nb_pred))

print("F1 Score:",
      f1_score(y_test, nb_pred))

Accuracy: 0.7420042643923241
Precision: 0.5101663585951941
Recall: 0.7379679144385026
F1 Score: 0.6032786885245902

In [20]:
# =========================================
# 20. Model Comparison Table
# =========================================

results = pd.DataFrame({

'Model':[
'Logistic Regression',
'Decision Tree',
'KNN',
'Naive Bayes'
],

'Accuracy':[

accuracy_score(y_test,lr_pred),

accuracy_score(y_test,dt_pred),

accuracy_score(y_test,knn_pred),

accuracy_score(y_test,nb_pred)

],

'Precision':[

precision_score(y_test,lr_pred),

precision_score(y_test,dt_pred),

precision_score(y_test,knn_pred),

precision_score(y_test,nb_pred)

],

'Recall':[

recall_score(y_test,lr_pred),

recall_score(y_test,dt_pred),

recall_score(y_test,knn_pred),

recall_score(y_test,nb_pred)

],

'F1_Score':[

f1_score(y_test,lr_pred),

f1_score(y_test,dt_pred),

f1_score(y_test,knn_pred),

f1_score(y_test,nb_pred)

]

})

results

                 Model  Accuracy  Precision    Recall  F1_Score
0  Logistic Regression  0.788202   0.616564  0.537433  0.574286
1        Decision Tree  0.731343   0.494924  0.521390  0.507812
2                  KNN  0.769723   0.568306  0.556150  0.562162
3          Naive Bayes  0.742004   0.510166  0.737968  0.603279

In [21]:
# =========================================
# 21. Best Model
# =========================================

results.sort_values(
    by='F1_Score',
    ascending=False
)

                 Model  Accuracy  Precision    Recall  F1_Score
3          Naive Bayes  0.742004   0.510166  0.737968  0.603279
0  Logistic Regression  0.788202   0.616564  0.537433  0.574286
2                  KNN  0.769723   0.568306  0.556150  0.562162
1        Decision Tree  0.731343   0.494924  0.521390  0.507812

In [22]:
# =========================================
# 22. Final Conclusion
# =========================================

print(
"Baseline model training completed successfully."
)

Baseline model training completed successfully.