<a href="https://colab.research.google.com/github/Saiful-2/telco-customer-churn/blob/main/notebooks/10_telco_hyperparameter_tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Telecom Customer Churn - Hyperparameter Tuning**

In [1]:
# =========================================
# 1. Import Required Libraries
# =========================================

import pandas as pd
import numpy as np

In [4]:
#

!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.2 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [5]:
# =========================================
# 2. Import Models
# =========================================

from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from lightgbm import LGBMClassifier

from catboost import CatBoostClassifier

from sklearn.svm import SVC

In [6]:
# =========================================
# 3. Import Hyperparameter Tuning Libraries
# =========================================

from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import RandomizedSearchCV

In [7]:
# =========================================
# 4. Import Evaluation Metrics
# =========================================

from sklearn.metrics import accuracy_score

from sklearn.metrics import precision_score

from sklearn.metrics import recall_score

from sklearn.metrics import f1_score

In [8]:
# =========================================
# 5. Load Training Dataset
# =========================================

X_train = pd.read_csv(
'https://raw.githubusercontent.com/Saiful-2/datasets/main/X_train_scaled.csv'
)

y_train = pd.read_csv(
'https://raw.githubusercontent.com/Saiful-2/datasets/main/y_train.csv'
)

In [9]:
# =========================================
# 6. Load Testing Dataset
# =========================================

X_test = pd.read_csv(
'https://raw.githubusercontent.com/Saiful-2/datasets/main/X_test_scaled.csv'
)

y_test = pd.read_csv(
'https://raw.githubusercontent.com/Saiful-2/datasets/main/y_test.csv'
)

In [10]:
# =========================================
# 7. Convert Target Variable into Series
# =========================================

y_train = y_train.squeeze()

y_test = y_test.squeeze()

In [11]:
# =========================================
# 8. Random Forest Hyperparameter Tuning
# =========================================

rf = RandomForestClassifier(
    random_state=42
)

rf_params = {

'n_estimators':[100,200,300],

'max_depth':[5,10,15],

'min_samples_split':[2,5,10],

'min_samples_leaf':[1,2,4]

}

rf_grid = GridSearchCV(

rf,

rf_params,

cv=5,

scoring='f1',

n_jobs=-1

)

rf_grid.fit(

X_train,

y_train

)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [5, 10, 15],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='f1')

In [12]:
# =========================================
# 9. Best Random Forest Parameters
# =========================================

rf_grid.best_params_

{'max_depth': 15,
 'min_samples_leaf': 4,
 'min_samples_split': 10,
 'n_estimators': 200}

In [13]:
# =========================================
# 10. Tuned Random Forest Prediction
# =========================================

rf_best = rf_grid.best_estimator_

rf_pred = rf_best.predict(
X_test
)

In [14]:
# =========================================
# 11. XGBoost Hyperparameter Tuning
# =========================================

xgb = XGBClassifier(

random_state=42,

eval_metric='logloss'

)

xgb_params = {

'n_estimators':[100,200],

'max_depth':[3,5,7],

'learning_rate':[0.01,0.05,0.1],

'subsample':[0.8,1.0]

}

xgb_random = RandomizedSearchCV(

xgb,

xgb_params,

n_iter=10,

cv=5,

scoring='f1',

random_state=42,

n_jobs=-1

)

xgb_random.fit(

X_train,

y_train

)

RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric='logloss',
                                           feature_types=None,
                                           feature_weights=None, gamma=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_cons...
                                           max_cat_to_onehot=None,
                                           max_delta_step=None, max_depth=None,
                                           max_leaves=None,
                                           min_child_weight=None, missing=nan,
                                           monotone_constraints=None,
                                           multi_strategy=None,
                                           n_estimators=None, n_jobs=None,
                                           num_parallel_tree=None, ...),
                   n_jobs=-1,
                   param_distributions={'learning_rate': [0.01, 0.05, 0.1],
                                        'max_depth': [3, 5, 7],
                                        'n_estimators': [100, 200],
                                        'subsample': [0.8, 1.0]},
                   random_state=42, scoring='f1')

In [15]:
# =========================================
# 12. Best XGBoost Parameters
# =========================================

xgb_random.best_params_

{'subsample': 0.8, 'n_estimators': 100, 'max_depth': 5, 'learning_rate': 0.05}

In [16]:
# =========================================
# 13. Tuned XGBoost Prediction
# =========================================

xgb_best = xgb_random.best_estimator_

xgb_pred = xgb_best.predict(
X_test
)

In [17]:
# =========================================
# 14. LightGBM Hyperparameter Tuning
# =========================================

lgbm = LGBMClassifier(
random_state=42
)

lgbm_params = {

'n_estimators':[100,200],

'max_depth':[5,10],

'learning_rate':[0.01,0.1],

'num_leaves':[31,50]

}

lgbm_random = RandomizedSearchCV(

lgbm,

lgbm_params,

n_iter=8,

cv=5,

scoring='f1',

random_state=42,

n_jobs=-1

)

lgbm_random.fit(

X_train,

y_train

)

[LightGBM] [Info] Number of positive: 1495, number of negative: 4130
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001013 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1186
[LightGBM] [Info] Number of data points in the train set: 5625, number of used features: 29
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.265778 -> initscore=-1.016151
[LightGBM] [Info] Start training from score -1.016151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

RandomizedSearchCV(cv=5, estimator=LGBMClassifier(random_state=42), n_iter=8,
                   n_jobs=-1,
                   param_distributions={'learning_rate': [0.01, 0.1],
                                        'max_depth': [5, 10],
                                        'n_estimators': [100, 200],
                                        'num_leaves': [31, 50]},
                   random_state=42, scoring='f1')

In [18]:
# =========================================
# 15. Best LightGBM Parameters
# =========================================

lgbm_random.best_params_

{'num_leaves': 31, 'n_estimators': 100, 'max_depth': 5, 'learning_rate': 0.1}

In [19]:
# =========================================
# 16. Tuned LightGBM Prediction
# =========================================

lgbm_best = lgbm_random.best_estimator_

lgbm_pred = lgbm_best.predict(
X_test
)

In [20]:
# =========================================
# 17. CatBoost Hyperparameter Tuning
# =========================================

cat = CatBoostClassifier(

verbose=0,

random_state=42

)

cat_params = {

'depth':[4,6,8],

'learning_rate':[0.01,0.05,0.1],

'iterations':[100,200]

}

cat_random = RandomizedSearchCV(

cat,

cat_params,

n_iter=8,

cv=5,

scoring='f1',

random_state=42,

n_jobs=-1

)

cat_random.fit(

X_train,

y_train

)

RandomizedSearchCV(cv=5,
                   estimator=CatBoostClassifier(random_state=42, verbose=0),
                   n_iter=8, n_jobs=-1,
                   param_distributions={'depth': [4, 6, 8],
                                        'iterations': [100, 200],
                                        'learning_rate': [0.01, 0.05, 0.1]},
                   random_state=42, scoring='f1')

In [21]:
# =========================================
# 18. Best CatBoost Parameters
# =========================================

cat_random.best_params_

{'learning_rate': 0.05, 'iterations': 100, 'depth': 8}

In [22]:
# =========================================
# 19. Tuned CatBoost Prediction
# =========================================

cat_best = cat_random.best_estimator_

cat_pred = cat_best.predict(
X_test
)

In [23]:
# =========================================
# 20. SVM Hyperparameter Tuning
# =========================================

svm = SVC(
probability=True
)

svm_params = {

'C':[0.1,1,10],

'kernel':['linear','rbf'],

'gamma':['scale','auto']

}

svm_grid = GridSearchCV(

svm,

svm_params,

cv=5,

scoring='f1',

n_jobs=-1

)

svm_grid.fit(

X_train,

y_train

)

GridSearchCV(cv=5, estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf']},
             scoring='f1')

In [24]:
# =========================================
# 21. Best SVM Parameters
# =========================================

svm_grid.best_params_

{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}

In [25]:
# =========================================
# 22. Tuned SVM Prediction
# =========================================

svm_best = svm_grid.best_estimator_

svm_pred = svm_best.predict(
X_test
)

In [26]:
# =========================================
# 23. Create Evaluation Function
# =========================================

def evaluate(

name,

y_true,

y_pred

):

    return [

    name,

    accuracy_score(
    y_true,
    y_pred
    ),

    precision_score(
    y_true,
    y_pred
    ),

    recall_score(
    y_true,
    y_pred
    ),

    f1_score(
    y_true,
    y_pred
    )

]

In [27]:
# =========================================
# 24. Tuned Model Performance Table
# =========================================

results = []

results.append(
evaluate(
'Tuned Random Forest',
y_test,
rf_pred
)
)

results.append(
evaluate(
'Tuned XGBoost',
y_test,
xgb_pred
)
)

results.append(
evaluate(
'Tuned LightGBM',
y_test,
lgbm_pred
)
)

results.append(
evaluate(
'Tuned CatBoost',
y_test,
cat_pred
)
)

results.append(
evaluate(
'Tuned SVM',
y_test,
svm_pred
)
)

tuned_results = pd.DataFrame(

results,

columns=[

'Model',

'Accuracy',

'Precision',

'Recall',

'F1 Score'

]

)

tuned_results

                 Model  Accuracy  Precision    Recall  F1 Score
0  Tuned Random Forest  0.790334   0.636678  0.491979  0.555053
1        Tuned XGBoost  0.796731   0.643791  0.526738  0.579412
2       Tuned LightGBM  0.793888   0.632911  0.534759  0.579710
3       Tuned CatBoost  0.798863   0.648208  0.532086  0.584435
4            Tuned SVM  0.776830   0.589820  0.526738  0.556497

In [28]:
# =========================================
# 25. Rank Models
# =========================================

tuned_results.sort_values(

'F1 Score',

ascending=False

)

                 Model  Accuracy  Precision    Recall  F1 Score
3       Tuned CatBoost  0.798863   0.648208  0.532086  0.584435
2       Tuned LightGBM  0.793888   0.632911  0.534759  0.579710
1        Tuned XGBoost  0.796731   0.643791  0.526738  0.579412
4            Tuned SVM  0.776830   0.589820  0.526738  0.556497
0  Tuned Random Forest  0.790334   0.636678  0.491979  0.555053

In [29]:
# =========================================
# 26. Final Conclusion
# =========================================

print(
'Hyperparameter tuning completed successfully.'
)

Hyperparameter tuning completed successfully.